### ISSUE TITLE
problem converting ctree into SAS

### ISSUE THREAD

**Issue by spedygiorgio** [az0/mlmeta#8]
I am using your code 4 converting ctree into SAS and receive the following error: 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘nodes’ for signature ‘"train", "numeric"’

**Comment by az0** [comment]
Could you please give a brief code example I could run?

Are you using ctree from partykit packge or from the party package?

**Comment by spedygiorgio** [comment]
It was a my fault. Your code works extremely properly. Just a suggestion, is it possible to substitute ' with " when grouping categorical covariates into  in ('FIRST', 'SECOND ITEM')?

**Comment by az0** [comment]
For yourself you can do ``` writeLines(gsub('"', "'", '"foo1","foo2"'))```, and if you think there is a reason to do this for all users, please open a new ticket
